server:
  port: ${PORT:8084}

spring:
  cloud:
    consul:
      host: localhost
      port: 8500

service:
  mock:
    base-url: https://jsonplaceholder.typicode.com
  kafka:
    base-url: http://127.0.0.1:9092